import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import html2canvas from 'html2canvas';

const AMBER = [255, 102, 0];
const BLACK = [10, 10, 10];
const WHITE = [255, 255, 255];
const GREY = [102, 102, 102];
const LIGHT_GREY = [242, 242, 242];
const GREEN_BG = [232, 245, 233];
const RED_BG = [255, 235, 238];
const WIN_COLOR = [0, 150, 68];
const LOSS_COLOR = [200, 20, 50];

function addHeader(doc, pageTitle, sessionName) {
  const w = doc.internal.pageSize.width;
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...BLACK);
  doc.text('FYNALYSE', 22, 14);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...GREY);
  doc.text(pageTitle, w - 22, 14, { align: 'right' });

  doc.setDrawColor(...AMBER);
  doc.setLineWidth(0.8);
  doc.line(22, 17, w - 22, 17);
}

function addFooter(doc, pageNum, sessionName) {
  const w = doc.internal.pageSize.width;
  const h = doc.internal.pageSize.height;

  doc.setDrawColor(...AMBER);
  doc.setLineWidth(0.5);
  doc.line(22, h - 18, w - 22, h - 18);

  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...GREY);
  doc.text(sessionName || 'TP/SL Pro Session', 22, h - 12);
  doc.text(`Page ${pageNum}`, w - 22, h - 12, { align: 'right' });
}

function sectionHeading(doc, title, y) {
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.3);
  doc.line(22, y - 2, doc.internal.pageSize.width - 22, y - 2);

  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...BLACK);
  doc.text(title, 22, y + 6);

  doc.setDrawColor(...BLACK);
  doc.setLineWidth(0.6);
  doc.line(22, y + 9, doc.internal.pageSize.width - 22, y + 9);

  return y + 16;
}

export async function generatePDF({ trades, stats, session, aiAnalysis, equityCurveId, chartsId, onProgress }) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const w = doc.internal.pageSize.width;
  const h = doc.internal.pageSize.height;
  const margin = 22;
  const sessionName = session?.name || 'Trading Session';
  const currency = session?.currency || 'USD';
  const startCapital = session?.startingCapital || 10000;
  const finalCapital = session?.currentCapital || startCapital;
  const dateStr = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  // ── PAGE 1: COVER ──────────────────────────────────────────────────
  onProgress?.('Building cover page...');

  doc.setFillColor(...BLACK);
  doc.rect(0, 0, w, h, 'F');

  doc.setFontSize(28);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...WHITE);
  doc.text('TP/SL PRO', w / 2, 70, { align: 'center' });

  doc.setFontSize(16);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...WHITE);
  doc.text('BACKTESTING PERFORMANCE REPORT', w / 2, 84, { align: 'center' });

  doc.setDrawColor(...AMBER);
  doc.setLineWidth(1.5);
  doc.line(margin, 92, w - margin, 92);

  doc.setFontSize(14);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...WHITE);
  doc.text(sessionName, w / 2, 106, { align: 'center' });

  doc.setFontSize(12);
  doc.setTextColor(...GREY);
  doc.text(dateStr, w / 2, 116, { align: 'center' });
  doc.text(`Starting Capital: $${startCapital.toLocaleString()}`, w / 2, 126, { align: 'center' });

  // 3 big stats
  const statsY = 155;
  const colW = (w - margin * 2) / 3;

  [[String(stats?.totalTrades || 0), 'TOTAL TRADES'],
   [(stats?.winRate?.toFixed(1) || '0') + '%', 'WIN RATE'],
   [(stats?.totalPnL >= 0 ? '+' : '') + '$' + (stats?.totalPnL?.toFixed(2) || '0'), 'SESSION P&L']
  ].forEach(([val, lbl], i) => {
    const cx = margin + colW * i + colW / 2;
    doc.setFontSize(26);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...AMBER);
    doc.text(val, cx, statsY, { align: 'center' });
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...GREY);
    doc.text(lbl, cx, statsY + 10, { align: 'center' });
  });

  doc.setDrawColor(40, 40, 40);
  doc.setLineWidth(0.3);
  doc.line(margin + colW, statsY - 18, margin + colW, statsY + 16);
  doc.line(margin + colW * 2, statsY - 18, margin + colW * 2, statsY + 16);

  doc.setFontSize(9);
  doc.setTextColor(60, 60, 60);
  doc.text('Generated by TP/SL Pro — fynalyse.com', w / 2, h - 20, { align: 'center' });

  // ── PAGE 2: PERFORMANCE SUMMARY ────────────────────────────────────
  onProgress?.('Compiling performance metrics...');
  doc.addPage();
  addHeader(doc, 'PERFORMANCE METRICS', sessionName);
  addFooter(doc, 2, sessionName);

  let y = sectionHeading(doc, 'PERFORMANCE METRICS', 26);

  const metricRows = [
    ['Total Trades', String(stats?.totalTrades || 0)],
    ['Wins', String(stats?.wins || 0)],
    ['Losses', String(stats?.losses || 0)],
    ['Win Rate', (stats?.winRate?.toFixed(1) || '0') + '%'],
    ['Total P&L ($)', (stats?.totalPnL >= 0 ? '+$' : '-$') + Math.abs(stats?.totalPnL || 0).toFixed(2)],
    ['Total P&L (%)', (stats?.totalPnLPct >= 0 ? '+' : '') + (stats?.totalPnLPct?.toFixed(2) || '0') + '%'],
    ['Average Win', '$' + (stats?.avgWin?.toFixed(2) || '0')],
    ['Average Loss', '-$' + (stats?.avgLoss?.toFixed(2) || '0')],
    ['Largest Win', '$' + (stats?.largestWin?.toFixed(2) || '0')],
    ['Largest Loss', '-$' + (stats?.largestLoss?.toFixed(2) || '0')],
    ['Max Drawdown ($)', '-$' + (stats?.maxDD?.toFixed(2) || '0')],
    ['Max Drawdown (%)', '-' + (stats?.maxDDPct?.toFixed(2) || '0') + '%'],
    ['Sharpe Ratio', stats?.sharpe?.toFixed(2) || '0'],
    ['Profit Factor', isFinite(stats?.profitFactor) ? stats?.profitFactor?.toFixed(2) : '∞'],
    ['Expectancy / Trade', (stats?.expectancy >= 0 ? '+$' : '-$') + Math.abs(stats?.expectancy || 0).toFixed(2)],
    ['Average R:R', '1 : ' + (stats?.avgRR?.toFixed(2) || '0')],
    ['Best SL Multiple', (stats?.bestSL || '—') + 'x'],
    ['Best TP Multiple', (stats?.bestTP || '—') + 'x'],
    ['Best Leverage', (stats?.bestLev || '—') + 'x'],
  ];

  autoTable(doc, {
    startY: y,
    margin: { left: margin, right: margin },
    head: [['METRIC', 'VALUE']],
    body: metricRows,
    styles: { font: 'helvetica', fontSize: 11, cellPadding: 3, lineColor: [220, 220, 220], lineWidth: 0.2 },
    headStyles: { fillColor: LIGHT_GREY, textColor: BLACK, fontStyle: 'bold', lineWidth: { bottom: 1 }, lineColor: { bottom: AMBER } },
    alternateRowStyles: { fillColor: [249, 249, 249] },
    columnStyles: {
      0: { textColor: GREY, fontStyle: 'normal' },
      1: { textColor: BLACK, fontStyle: 'bold', halign: 'right' },
    },
  });

  // ── PAGE 3: EQUITY CURVE ───────────────────────────────────────────
  onProgress?.('Capturing equity curve...');
  doc.addPage();
  addHeader(doc, 'EQUITY CURVE', sessionName);
  addFooter(doc, 3, sessionName);
  y = sectionHeading(doc, 'EQUITY CURVE', 26);

  const equityEl = document.getElementById(equityCurveId);
  if (equityEl) {
    try {
      const canvas = await html2canvas(equityEl, { backgroundColor: '#111111', scale: 1.5 });
      const imgData = canvas.toDataURL('image/png');
      const imgH = (canvas.height / canvas.width) * (w - margin * 2);
      doc.addImage(imgData, 'PNG', margin, y + 2, w - margin * 2, Math.min(imgH, 90));
      y = y + Math.min(imgH, 90) + 8;
    } catch (e) {}
  }

  const chartCaption = `Equity curve showing capital progression across ${trades.length} trades. Green dots represent winning trades, red dots represent losing trades. Dashed line indicates starting capital of $${startCapital.toLocaleString()}.`;
  doc.setFontSize(9);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(...GREY);
  const lines = doc.splitTextToSize(chartCaption, w - margin * 2);
  doc.text(lines, margin, y + 4);
  y += lines.length * 5 + 10;

  const peakCapital = Math.max(...(stats?.capitals || [startCapital]));
  const lowestCapital = Math.min(...(stats?.capitals || [startCapital]));

  autoTable(doc, {
    startY: y,
    margin: { left: margin, right: margin },
    head: [['METRIC', 'VALUE']],
    body: [
      ['Starting Capital', '$' + startCapital.toLocaleString()],
      ['Peak Capital', '$' + peakCapital.toFixed(2)],
      ['Lowest Capital', '$' + lowestCapital.toFixed(2)],
      ['Final Capital', '$' + finalCapital.toFixed(2)],
    ],
    styles: { font: 'helvetica', fontSize: 10, cellPadding: 2.5 },
    headStyles: { fillColor: LIGHT_GREY, textColor: BLACK, fontStyle: 'bold' },
    columnStyles: { 0: { textColor: GREY }, 1: { textColor: BLACK, fontStyle: 'bold', halign: 'right' } },
  });

  // ── PAGE 4: DISTRIBUTION CHARTS ────────────────────────────────────
  onProgress?.('Capturing distribution charts...');
  doc.addPage();
  addHeader(doc, 'TRADE DISTRIBUTION', sessionName);
  addFooter(doc, 4, sessionName);
  y = sectionHeading(doc, 'TRADE DISTRIBUTION ANALYSIS', 26);

  const chartsEl = document.getElementById(chartsId);
  if (chartsEl) {
    try {
      const canvas = await html2canvas(chartsEl, { backgroundColor: '#0a0a0a', scale: 1.2 });
      const imgData = canvas.toDataURL('image/png');
      const maxH = h - y - 40;
      const imgH = Math.min((canvas.height / canvas.width) * (w - margin * 2), maxH);
      doc.addImage(imgData, 'PNG', margin, y + 2, w - margin * 2, imgH);
    } catch (e) {}
  }

  // ── PAGE 5: FULL TRADE LOG ─────────────────────────────────────────
  onProgress?.('Rendering trade log...');
  doc.addPage();
  addHeader(doc, 'COMPLETE TRADE LOG', sessionName);
  addFooter(doc, 5, sessionName);
  y = sectionHeading(doc, 'COMPLETE TRADE LOG', 26);

  const tradeRows = trades.map(t => [
    t.tradeNum,
    t.direction,
    t.entryPrice?.toFixed(4),
    t.atr?.toFixed(4),
    t.slMultiple + 'x',
    t.tpMultiple + 'x',
    t.leverage + 'x',
    t.slPrice?.toFixed(4),
    t.tpPrice?.toFixed(4),
    '1:' + t.rr?.toFixed(2),
    t.outcome,
    (t.pnl >= 0 ? '+$' : '-$') + Math.abs(t.pnl).toFixed(2),
    '$' + t.capitalAfter?.toFixed(2),
  ]);

  autoTable(doc, {
    startY: y,
    margin: { left: margin, right: margin },
    head: [['#', 'DIR', 'ENTRY', 'ATR', 'SL', 'TP', 'LEV', 'SL $', 'TP $', 'R:R', 'RESULT', 'P&L', 'CAPITAL']],
    body: tradeRows,
    styles: { font: 'helvetica', fontSize: 8, cellPadding: 1.5, lineColor: [220, 220, 220], lineWidth: 0.2 },
    headStyles: { fillColor: LIGHT_GREY, textColor: BLACK, fontStyle: 'bold', fontSize: 8 },
    bodyStyles: { textColor: BLACK },
    didParseCell(data) {
      if (data.section === 'body') {
        const row = trades[data.row.index];
        if (row?.outcome === 'WIN') data.cell.styles.fillColor = GREEN_BG;
        else if (row?.outcome === 'LOSS') data.cell.styles.fillColor = RED_BG;
      }
    },
    didDrawPage(data) {
      addHeader(doc, 'COMPLETE TRADE LOG', sessionName);
      addFooter(doc, doc.internal.getNumberOfPages(), sessionName);
    },
  });

  // ── PAGE 6: AI ANALYSIS ────────────────────────────────────────────
  onProgress?.('Formatting AI analysis...');
  if (aiAnalysis) {
    doc.addPage();
    addHeader(doc, 'AI STRATEGY ANALYSIS', sessionName);
    addFooter(doc, doc.internal.getNumberOfPages(), sessionName);
    y = sectionHeading(doc, 'AI STRATEGY ANALYSIS', 26);

    doc.setFontSize(9);
    doc.setFont('helvetica', 'italic');
    doc.setTextColor(...GREY);
    doc.text('Analysis generated by Claude AI based on complete session data', margin, y);
    y += 8;

    // Win/Loss ratio
    const wins = trades.filter(t => t.outcome === 'WIN').length;
    const losses = trades.filter(t => t.outcome === 'LOSS').length;
    const wr = trades.length > 0 ? (wins / trades.length * 100).toFixed(0) : 0;
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...BLACK);
    doc.text(`${wins}W / ${losses}L = ${wr}%`, margin, y + 10);
    y += 18;

    // Parse and render sections
    const lines = aiAnalysis.split('\n');
    const SECTIONS_UPPER = ['STRATEGY OVERVIEW', 'SL MULTIPLE ANALYSIS', 'TP MULTIPLE ANALYSIS', 'LEVERAGE ASSESSMENT', 'DIRECTIONAL BIAS', 'PATTERN OBSERVATIONS', 'RISK MANAGEMENT SCORE', 'THREE RECOMMENDATIONS', 'VERDICT'];

    let current = null;
    const parsed = [];
    for (const line of lines) {
      const match = SECTIONS_UPPER.find(s => line.toUpperCase().startsWith(s + ':') || line.toUpperCase() === s + ':');
      if (match) {
        if (current) parsed.push(current);
        current = { title: match, content: line.replace(new RegExp(`^${match}:?\\s*`, 'i'), '').trim() };
      } else if (current) {
        current.content += (current.content ? '\n' : '') + line;
      }
    }
    if (current) parsed.push(current);

    const verdict = parsed.find(s => s.title === 'VERDICT');

    for (const section of parsed.filter(s => s.title !== 'VERDICT')) {
      if (y > h - 50) {
        doc.addPage();
        addHeader(doc, 'AI STRATEGY ANALYSIS', sessionName);
        addFooter(doc, doc.internal.getNumberOfPages(), sessionName);
        y = 28;
      }
      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...BLACK);
      doc.text(section.title, margin, y);
      y += 6;

      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(40, 40, 40);
      const wrapped = doc.splitTextToSize(section.content.trim(), w - margin * 2);
      doc.text(wrapped, margin, y);
      y += wrapped.length * 5 + 6;
    }

    // Verdict box
    if (verdict) {
      if (y > h - 40) {
        doc.addPage();
        addHeader(doc, 'AI STRATEGY ANALYSIS', sessionName);
        addFooter(doc, doc.internal.getNumberOfPages(), sessionName);
        y = 28;
      }
      y += 4;
      doc.setDrawColor(...BLACK);
      doc.setLineWidth(1);
      doc.setFillColor(...AMBER);
      doc.rect(margin, y, w - margin * 2, 18, 'FD');
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...WHITE);
      doc.text(verdict.content.trim(), w / 2, y + 11, { align: 'center' });
    }
  }

  // ── DOWNLOAD ──────────────────────────────────────────────────────
  onProgress?.('Download ready.');
  const filename = `TP-SL-Pro-Report-${(sessionName || 'Session').replace(/\s+/g, '-')}-${new Date().toISOString().slice(0, 10)}.pdf`;
  doc.save(filename);
  return filename;
}
