import { calcTrade, applyTradeOutcome } from './calculations.js';

export function createTradeRecord({ tradeNum, direction, entryPrice, atr, slMultiple, tpMultiple, leverage, capital, outcome }) {
  const calc = calcTrade({ direction, entryPrice, atr, slMultiple, tpMultiple, leverage, capital });
  const pnl = outcome === 'WIN' ? calc.maxGain : -calc.maxLoss;
  const capitalAfter = capital + pnl;

  return {
    tradeNum,
    timestamp: Date.now(),
    direction,
    entryPrice: parseFloat(entryPrice),
    atr: parseFloat(atr),
    slMultiple: parseFloat(slMultiple),
    tpMultiple: parseFloat(tpMultiple),
    leverage: parseFloat(leverage),
    slPrice: calc.slPrice,
    tpPrice: calc.tpPrice,
    rr: calc.rr,
    outcome,
    pnl,
    capitalAfter,
    positionSize: calc.positionSize,
    maxLoss: calc.maxLoss,
    maxGain: calc.maxGain,
  };
}

export function exportCSV(trades, sessionName) {
  const headers = ['#', 'Timestamp', 'Direction', 'Entry', 'ATR', 'SL Mult', 'TP Mult', 'Leverage', 'SL Price', 'TP Price', 'R:R', 'Outcome', 'P&L ($)', 'Capital After'];
  const rows = trades.map(t => [
    t.tradeNum,
    new Date(t.timestamp).toISOString(),
    t.direction,
    t.entryPrice,
    t.atr,
    t.slMultiple,
    t.tpMultiple,
    t.leverage,
    t.slPrice?.toFixed(4),
    t.tpPrice?.toFixed(4),
    t.rr?.toFixed(2),
    t.outcome,
    t.pnl?.toFixed(2),
    t.capitalAfter?.toFixed(2),
  ]);

  const csv = [headers, ...rows].map(r => r.join(',')).join('\n');
  const blob = new Blob([csv], { type: 'text/csv' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `TP-SL-Pro-Trades-${sessionName || 'Session'}-${new Date().toISOString().slice(0, 10)}.csv`;
  a.click();
  URL.revokeObjectURL(url);
}

export function downloadCSVTemplate() {
  const headers = ['Direction', 'Entry Price', 'ATR', 'SL Multiple', 'TP Multiple', 'Leverage', 'Outcome'];
  const example = ['LONG', '1.2345', '0.0050', '1.0', '2.0', '1', 'WIN'];
  const csv = [headers, example].map(r => r.join(',')).join('\n');
  const blob = new Blob([csv], { type: 'text/csv' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'TP-SL-Pro-Template.csv';
  a.click();
  URL.revokeObjectURL(url);
}

export function parseCSV(text) {
  const lines = text.trim().split('\n');
  if (lines.length < 2) return [];
  const rows = lines.slice(1).map((line, i) => {
    const cols = line.split(',').map(c => c.trim());
    return {
      id: i + 1,
      direction: cols[0]?.toUpperCase() === 'SHORT' ? 'SHORT' : 'LONG',
      entryPrice: cols[1] || '',
      atr: cols[2] || '',
      slMultiple: cols[3] || '1.0',
      tpMultiple: cols[4] || '2.0',
      leverage: cols[5] || '1',
      outcome: cols[6]?.toUpperCase() === 'LOSS' ? 'LOSS' : 'WIN',
    };
  });
  return rows;
}

export function shareSummary(stats, sessionName, currency) {
  const text = `📊 TP/SL PRO — ${sessionName || 'Trading Session'}
━━━━━━━━━━━━━━━━━━━━
Total Trades: ${stats.totalTrades}
Win Rate: ${stats.winRate?.toFixed(1)}%
Total P&L: ${stats.totalPnL >= 0 ? '+' : ''}$${stats.totalPnL?.toFixed(2)}
Profit Factor: ${stats.profitFactor?.toFixed(2)}
Max Drawdown: ${stats.maxDDPct?.toFixed(1)}%
Sharpe Ratio: ${stats.sharpe?.toFixed(2)}
━━━━━━━━━━━━━━━━━━━━
Generated by TP/SL Pro`;

  navigator.clipboard.writeText(text).catch(() => {
    const el = document.createElement('textarea');
    el.value = text;
    document.body.appendChild(el);
    el.select();
    document.execCommand('copy');
    document.body.removeChild(el);
  });
}
